before_install:
  - "gem update --system"
  - "gem install bundler"
script:
  - "travis_retry bundle exec rake default --trace"
  - "bundle exec rubocop -D"
language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3
  - 2.4
  - 2.5
gemfile: travis.gemfile
env:
  global:
  - TRAVISCI=1
