script: "bundle exec rake neo4j:install[community-2.3.0] neo4j:start default --trace"
language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.0
  - 2.3.0
gemfile: travis.gemfile
env:
  global:
  - TRAVISCI=1
  matrix:
  - NEO4J_VERSION=6.0.9
  - NEO4J_VERSION=7.2.3
  - NEO4J_VERSION=8.1.3
